//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillBuyDetail
    {
        public int idBillBuy { get; set; }
        public int idItem { get; set; }
        public string classify { get; set; }
        public int amount { get; set; }
        public int remainAmount { get; set; }
        public string amountCount { get; set; }
        public string status { get; set; }
        public string note { get; set; }
        public decimal singlePrice { get; set; }
    
        public virtual BillBuy BillBuy { get; set; }
        public virtual ItemClassify ItemClassify { get; set; }
    }
}
