//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cost
    {
        public int month { get; set; }
        public int year { get; set; }
        public Nullable<decimal> premiseCost { get; set; }
        public Nullable<decimal> electricityCost { get; set; }
        public Nullable<decimal> waterCost { get; set; }
        public Nullable<decimal> totalFundCost { get; set; }
        public Nullable<decimal> bankInterestExpensePercent { get; set; }
        public Nullable<decimal> totalTaxCost { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<decimal> totalIncome { get; set; }
    }
}
