//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Acounts = new HashSet<Acount>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> birthDay { get; set; }
        public int identityCardNumber { get; set; }
        public Nullable<System.DateTime> startDay { get; set; }
        public Nullable<System.DateTime> endDay { get; set; }
        public string status { get; set; }
        public int age { get; set; }
        public string post { get; set; }
        public Nullable<decimal> salary { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acount> Acounts { get; set; }
    }
}
